### ISSUE TITLE
How can I make this grey border be transparent as well?

### ISSUE THREAD

**Issue by nshern** [zenbones-theme/zenbones.nvim#173]
Using [zen-mode](https://github.com/folke/zen-mode.nvim) in neovim v0.10.0-dev-3100+gd3fa88b70-Homebrew

![Screenshot 2024-05-09 at 10 54 39](https://github.com/mcchrish/zenbones.nvim/assets/90867839/1a93575f-1a62-4fcf-92f9-b04eba657760)

**Comment by nshern** [comment]
It is not happening when using Neovim stable release, so might be an issue with neovim?

**Comment by mcchrish** [comment]
I think this is an issue with zen mode https://github.com/folke/zen-mode.nvim/issues/115.
You can set you backdrop to 1 to be the same as `Normal` if the bug is resolved.
