### ISSUE TITLE
The color of the colorcolumn looks a little odd?

### ISSUE THREAD

**Issue by nanozuki** [zenbones-theme/zenbones.nvim#182]
I love this color scheme! However, the color column's color seems too colorful compared to the background. And the color is always the same in different variants. Is this a bug?

<img width="702" alt="image" src="https://github.com/mcchrish/zenbones.nvim/assets/4208028/732fecd6-cc8e-405c-a317-61a6bc1ebcbb">
<img width="727" alt="image" src="https://github.com/mcchrish/zenbones.nvim/assets/4208028/3c0fc777-a1ec-4e59-9dbe-75e366bc65d7">

**Comment by mcchrish** [comment]
I went with a colorful `colorcolumn` to disguish it from `cursorcolumn` and vertical splits divider. I guess the color is too strong then I'm open for adjustments.
