### ISSUE TITLE
String colour has changed in a recent commit.

### ISSUE THREAD

**Issue by arnevm123** [zenbones-theme/zenbones.nvim#194]
Hi,

in PR #183 this line was changed:
`lua/zenbones/specs/dark.lua:217`

``` lua
+ sym "@string"                       { Constant },
- sym "@string"                       { String },
```

This seems to have changes all strings from grey to light blue (Seoulbones, dark).

This looks like a wanted change, but I did prefer the old look, so I just wanted to double check with you.

Anyway, this seems to revert to the old color scheme for anyone also preferring the old colors: 
``` lua
vim.api.nvim_set_hl(0, "@string", { link = "Constant" })
```

**Comment by mcchrish** [comment]
Yes, this is intended and it makes the color consistent between the regex syntax and treesitter.
But it's nice how easy it is to customize it back.
