### ISSUE TITLE
Add support for nvim-dap-ui

### ISSUE THREAD

**Issue by jryom** [zenbones-theme/zenbones.nvim#203]
https://github.com/rcarriga/nvim-dap-ui

**Comment by mcchrish** [comment]
For reference, here's the highlight group https://github.com/rcarriga/nvim-dap-ui/blob/ffa89839f97bad360e78428d5c740fdad9a0ff02/lua/dapui/config/highlights.lua#L17-L49.
I personally don't use dap-ui to know which mapping looks good, but PR is welcome.

**Comment by jryom** [comment]
Yeah, and sorry for the brief description btw. I was planning on adding it myself, will open a PR at some point soon :)
