### ISSUE TITLE
Add support for neotest

### ISSUE THREAD

**Issue by jryom** [zenbones-theme/zenbones.nvim#204]
https://github.com/nvim-neotest/neotest

**Comment by mcchrish** [comment]
I think it's relatively simple to map them https://github.com/nvim-neotest/neotest/blob/6d3d22cdad49999ef774ebe1bc250a4994038964/lua/neotest/config/init.lua#L6-L22. I personally don't use neotest so I don't have a good understanding to properly assign which color looks best. A PR is welcome.
